version: '3'
services:
# Frontend node server
  frontend:
    image: velden.azurecr.io/solution_frontend
    depends_on:
      - server
      - proxy
    ports:
      - 4200:80
    networks:
      - envoymesh
    volumes:
      - ./QinIssue.Frontend:/usr/src/app:rw
# GPRC Server
  server:
    image: velden.azurecr.io/solution_server
    ports:
      - 50051:50051
    networks:
      - envoymesh
# Envoy Proxy - GRCP web conversion for frontend
  proxy:
    image: envoyproxy/envoy-alpine
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh

networks:
  envoymesh: {}
  
