version: '3'
services:
# Frontend node server
  frontend:
    build: ./QinIssue.Frontend
    depends_on:
      - server
      - proxy
    ports:
      - 4200:4200
    networks:
      - envoymesh
    volumes:
      - ./QinIssue.Frontend:/usr/src/app:rw
# GPRC Server
  server:
    build: .
    ports:
      - 50051:50051
    networks:
      - envoymesh
# Envoy Proxy - GRCP web conversion for frontend
  proxy:
    image: envoyproxy/envoy-alpine
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoymesh

networks:
  envoymesh: {}
  
